# fly.toml app configuration file generated for cgm-remote-monitor--2gqgq on 2024-12-14T18:26:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cgm-remote-monitor--2gqgq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
